<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="decl">
    <xs:annotation>
      <xs:documentation>Elemento que encapsula la información del formulario 1011 INFORMACION DE LAS DECLARACIONES TRIBUTARIAS</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="cpt" use="required">
        <xs:annotation>
          <xs:documentation>Concepto</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="sal" use="required">
        <xs:annotation>
          <xs:documentation>Saldos al 31 de diciembre</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="mas">
    <xs:annotation>
      <xs:documentation>Elemento raiz del xml de carga masiva</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cab" type="CabType"/>
        <xs:element ref="decl" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="CabType">
    <xs:sequence>
      <xs:element name="Ano" type="xs:gYear" nillable="false">
        <xs:annotation>
          <xs:documentation>Año de envio</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CodCpt" nillable="false">
        <xs:annotation>
          <xs:documentation>Concepto</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Formato" fixed="1011">
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Version" type="xs:positiveInteger" fixed="6"/>
      <xs:element name="NumEnvio">
        <xs:annotation>
          <xs:documentation>Numero de envio</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="8"/>
            <xs:maxInclusive value="99999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FecEnvio" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation>Fecha de envio</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FecInicial" type="xs:date">
        <xs:annotation>
          <xs:documentation>Fecha inicial</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FecFinal" type="xs:date">
        <xs:annotation>
          <xs:documentation>Fecha Final</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ValorTotal" type="xs:double">
        <xs:annotation>
          <xs:documentation>Valor Total</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CantReg">
        <xs:annotation>
          <xs:documentation>Cantidad de registros</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="4"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>