<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ingresos">
		<xs:annotation>
			<xs:documentation>Elemento que encapsula la información del formulario 1647v1Información de Ingresos Recibidos para Terceros</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="con" use="required">
				<xs:annotation>
					<xs:documentation>Concepto</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-9]{1,4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tdoc" use="required">
				<xs:annotation>
					<xs:documentation>Tipo de Documento</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-9]{1,2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nid" use="required">
				<xs:annotation>
					<xs:documentation>Número de Identificación del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						 <xs:pattern value="[a-zA-Z0-9]+"/>
						<xs:minLength value="1"/>
						<xs:maxLength value="20"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="dv" use="optional">
				<xs:annotation>
					<xs:documentation>Digito de Verificación</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="apl1" use="optional">
				<xs:annotation>
					<xs:documentation>Primer Apellido del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="apl2" use="optional">
				<xs:annotation>
					<xs:documentation>Segundo Apellido del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nom1" use="optional">
				<xs:annotation>
					<xs:documentation>Primer nombre del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nom2" use="optional">
				<xs:annotation>
					<xs:documentation>Otros nombres del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="raz" use="optional">
				<xs:annotation>
					<xs:documentation>Razón social del informado</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="450"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="pais" use="required">
				<xs:annotation>
					<xs:documentation>País de Residencia o domicilio</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{0,4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="vtotal" use="required">
				<xs:annotation>
					<xs:documentation>Valor total de la operación</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:pattern value="[0-9]{1,18}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ving" use="required">
				<xs:annotation>
					<xs:documentation>Valor ingreso reintegrado transferido distribuido al tercero </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:pattern value="[0-9]{1,18}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="vret" use="required">
				<xs:annotation>
					<xs:documentation>Valor Retención reintegrada transferida distribuida al tercero </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:pattern value="[0-9]{1,18}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tdoc2" use="required">
				<xs:annotation>
					<xs:documentation>Tipo de documento del  tercero beneficiario ingreso</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-9]{1,2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nid2i" use="required">
				<xs:annotation>
					<xs:documentation>Identificación  del tercero beneficiario ingreso</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z0-9]+"/>
						<xs:minLength value="0"/>
						<xs:maxLength value="20"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="apl1i" use="optional">
				<xs:annotation>
					<xs:documentation>Primer apellido del tercero para quien se recibió ingreso </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="apl2i" use="optional">
				<xs:annotation>
					<xs:documentation>Segundo apellido  del tercero para quien se recibió ingreso </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nom1i" use="optional">
				<xs:annotation>
					<xs:documentation>Primer nombre del tercero para quien se recibió ingreso </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="nom2i" use="optional">
				<xs:annotation>
					<xs:documentation>Otros nombres del tercero para quien se recibió ingreso </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="60"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="razi" use="optional">
				<xs:annotation>
					<xs:documentation>Razón social del tercero para quien se recibió ingreso </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="450"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="dir" use="optional">
				<xs:annotation>
					<xs:documentation>Dirección</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="200"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cdpt" use="optional">
				<xs:annotation>
					<xs:documentation>Código del Departamento</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{0,2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cmcp" use="optional">
				<xs:annotation>
					<xs:documentation>Código del Municipio</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{0,3}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="paist" use="required">
				<xs:annotation>
					<xs:documentation>País de Residencia o domicilio</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9]{0,4}"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="mas">
		<xs:annotation>
			<xs:documentation>Elemento raiz del xml de carga masiva</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Cab" type="CabType"/>
				<xs:element ref="ingresos" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CabType">
		<xs:sequence>
			<xs:element name="Ano" type="xs:gYear" nillable="false">
				<xs:annotation>
					<xs:documentation>Año de envio</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CodCpt" nillable="false">
				<xs:annotation>
					<xs:documentation>Concepto</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="99"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Formato" fixed="1647">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:totalDigits value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Version" type="xs:positiveInteger" fixed="2"/>
			<xs:element name="NumEnvio">
				<xs:annotation>
					<xs:documentation>Numero de envio</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:totalDigits value="8"/>
						<xs:maxInclusive value="99999999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FecEnvio" type="xs:dateTime">
				<xs:annotation>
					<xs:documentation>Fecha de envio</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FecInicial" type="xs:date">
				<xs:annotation>
					<xs:documentation>Fecha inicial</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FecFinal" type="xs:date">
				<xs:annotation>
					<xs:documentation>Fecha Final</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ValorTotal" type="xs:long">
				<xs:annotation>
					<xs:documentation>Valor Total</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CantReg">
				<xs:annotation>
					<xs:documentation>Cantidad de registros</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:totalDigits value="4"/>
						<xs:maxInclusive value="9999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>